version: "0.1"
services:
  discord-bot:
    build: .
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=[INSERT_BOT_TOKEN]
    restart: unless-stopped
    volumes:
      - ./data:/data
